# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import json

# ---------------------------------------------------------
# LOAD YOUR EXISTING DATA
# ---------------------------------------------------------

try:
    planet_data = planet_df.to_dict(orient="records")
except:
    planet_data = []

try:
    satellite_data = satellite_df.to_dict(orient="records")
except:
    satellite_data = []

planets_json = json.dumps(planet_data)
satellites_json = json.dumps(satellite_data)

# ---------------------------------------------------------
# FULL INTERACTIVE KISHANSKY APPLICATION
# ---------------------------------------------------------

app = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<style>

html, body {{
    margin: 0;
    padding: 0;
    overflow: hidden;
    background: #000;
}}

#app {{
    width: 100vw;
    height: 850px;
    position: relative;
    overflow: hidden;
    background:
        radial-gradient(
            circle at center,
            #111827 0%,
            #020617 50%,
            #000 100%
        );
}}

#sky {{
    position: absolute;
    width: 100%;
    height: 100%;
    left: 0;
    top: 0;
}}

#title {{
    position: absolute;
    top: 20px;
    left: 25px;
    color: white;
    font-family: Arial;
    font-size: 24px;
    font-weight: bold;
    z-index: 10;
}}

#info {{
    position: absolute;
    right: 25px;
    top: 80px;
    width: 280px;
    padding: 20px;
    color: white;
    background: rgba(0,0,0,.85);
    border: 1px solid #555;
    border-radius: 12px;
    font-family: Arial;
    display: none;
    z-index: 10;
}}

#controls {{
    position: absolute;
    bottom: 20px;
    left: 50%;
    transform: translateX(-50%);
    z-index: 10;
}}

button {{
    padding: 10px 18px;
    margin: 4px;
    border-radius: 7px;
    border: 1px solid #555;
    background: #1f2937;
    color: white;
    cursor: pointer;
}}

</style>

</head>

<body>

<div id="app">

<canvas id="sky"></canvas>

<div id="title">
🌌 KISHANSKY OBSERVATORY
</div>

<div id="info">

<h2 id="name">
Selected Object
</h2>

<p>
Type:
<span id="type"></span>
</p>

<p>
Altitude:
<span id="altitude"></span>
</p>

<p>
Azimuth:
<span id="azimuth"></span>
</p>

<p>
Distance:
<span id="distance"></span>
</p>

</div>

<div id="controls">

<button onclick="zoomIn()">
Zoom In
</button>

<button onclick="zoomOut()">
Zoom Out
</button>

<button onclick="resetView()">
Reset View
</button>

</div>

</div>

<script>

const canvas =
document.getElementById("sky");

const ctx =
canvas.getContext("2d");

let width =
window.innerWidth;

let height =
850;

canvas.width =
width;

canvas.height =
height;

let zoom = 1;

let offsetX = 0;

let offsetY = 0;

let selected = null;

const planets =
{planets_json};

const satellites =
{satellites_json};

let objects = [

    ...planets,

    ...satellites

];


// -------------------------------------
// STAR FIELD
// -------------------------------------

let stars = [];

for (
    let i = 0;
    i < 3000;
    i++
) {{

    stars.push({{

        x: Math.random(),

        y: Math.random(),

        size:
        Math.random() * 2,

        brightness:
        Math.random()

    }});

}}


// -------------------------------------
// SKY COORDINATES
// -------------------------------------

function convert(
    altitude,
    azimuth
) {{

    const cx =
    width / 2 + offsetX;

    const cy =
    height / 2 + offsetY;

    const radius =
    Math.min(
        width,
        height
    )
    * .38
    * zoom;

    const r =
    radius *
    (90 - altitude)
    / 90;

    const angle =
    (azimuth - 90)
    * Math.PI
    / 180;

    return {{

        x:
        cx +
        r *
        Math.cos(angle),

        y:
        cy +
        r *
        Math.sin(angle)

    }};

}}


// -------------------------------------
// DRAW STARS
// -------------------------------------

function drawStars() {{

    for (
        let star of stars
    ) {{

        ctx.beginPath();

        ctx.arc(

            star.x * width,

            star.y * height,

            star.size,

            0,

            Math.PI * 2

        );

        ctx.fillStyle =

        "rgba(255,255,255," +

        (

            .25

            +

            star.brightness
            * .75

        )

        + ")";

        ctx.fill();

    }}

}}


// -------------------------------------
// DRAW SKY
// -------------------------------------

function drawSky() {{

    const cx =
    width / 2 + offsetX;

    const cy =
    height / 2 + offsetY;

    const radius =
    Math.min(
        width,
        height
    )
    * .38
    * zoom;

    ctx.strokeStyle =
    "rgba(150,170,220,.25)";

    ctx.lineWidth = 1;

    ctx.beginPath();

    ctx.arc(

        cx,

        cy,

        radius,

        0,

        Math.PI * 2

    );

    ctx.stroke();

    for (
        let altitude = 30;
        altitude < 90;
        altitude += 30
    ) {{

        const r =
        radius *
        (90 - altitude)
        / 90;

        ctx.beginPath();

        ctx.arc(

            cx,

            cy,

            r,

            0,

            Math.PI * 2

        );

        ctx.stroke();

    }}

    ctx.fillStyle =
    "white";

    ctx.font =
    "bold 18px Arial";

    ctx.fillText(
        "N",
        cx - 7,
        cy - radius - 15
    );

    ctx.fillText(
        "E",
        cx + radius + 15,
        cy
    );

    ctx.fillText(
        "S",
        cx - 7,
        cy + radius + 25
    );

    ctx.fillText(
        "W",
        cx - radius - 25,
        cy
    );

}}


// -------------------------------------
// DRAW OBJECTS
// -------------------------------------

function drawObjects(){{

    for (
        let object of objects
    ) {{

        if (
            object.altitude <= 0
        )
        continue;

        const p =
        convert(

            object.altitude,

            object.azimuth

        );

        const selectedObject =

        selected &&

        selected.name ===
        object.name;

        let size =

        object.type ===
        "Planet"

        ? 11
        : 5;

        if (
            selectedObject
        )
        size = 14;

        ctx.beginPath();

        ctx.arc(

            p.x,

            p.y,

            size,

            0,

            Math.PI * 2

        );

        ctx.fillStyle =

        object.type ===
        "Planet"

        ? "white"
        : "#9da8ff";

        ctx.shadowBlur =

        selectedObject
        ? 35
        : 12;

        ctx.shadowColor =
        "white";

        ctx.fill();

        ctx.shadowBlur = 0;

        if (
            object.type ===
            "Planet"
            ||
            selectedObject
        ) {{

            ctx.fillStyle =
            "white";

            ctx.font =
            "13px Arial";

            ctx.fillText(

                object.name,

                p.x + 15,

                p.y

            );

        }}

    }}

}}


// -------------------------------------
// RENDER LOOP
// -------------------------------------

function render() {{

    ctx.fillStyle =
    "#020617";

    ctx.fillRect(

        0,

        0,

        width,

        height

    );

    drawStars();

    drawSky();

    drawObjects();

    requestAnimationFrame(
        render
    );

}}

render();


// -------------------------------------
// CLICK TO SELECT
// -------------------------------------

canvas.addEventListener(

    "click",

    function(event) {{

        let closest = null;

        let closestDistance = 35;

        for (
            let object of objects
        ) {{

            if (
                object.altitude <= 0
            )
            continue;

            const p =
            convert(

                object.altitude,

                object.azimuth

            );

            const distance =

            Math.sqrt(

                (

                    event.clientX -
                    p.x

                ) ** 2

                +

                (

                    event.clientY -
                    p.y

                ) ** 2

            );

            if (
                distance <
                closestDistance
            ) {{

                closest =
                object;

                closestDistance =
                distance;

            }}

        }}

        if (
            closest
        ) {{

            selected =
            closest;

            document.getElementById(
                "info"
            ).style.display =
            "block";

            document.getElementById(
                "name"
            ).innerText =
            closest.name;

            document.getElementById(
                "type"
            ).innerText =
            closest.type || "Satellite";

            document.getElementById(
                "altitude"
            ).innerText =

            Number(
                closest.altitude
            ).toFixed(3)
            + "°";

            document.getElementById(
                "azimuth"
            ).innerText =

            Number(
                closest.azimuth
            ).toFixed(3)
            + "°";

            document.getElementById(
                "distance"
            ).innerText =

            Number(
                closest.distance
            ).toFixed(2)
            + " km";

        }}

    }}

);


// -------------------------------------
// ZOOM
// -------------------------------------

function zoomIn() {{

    zoom *= 1.3;

}}

function zoomOut() {{

    zoom /= 1.3;

}}

function resetView() {{

    zoom = 1;

    offsetX = 0;

    offsetY = 0;

}}


// -------------------------------------
// MOUSE PAN
// -------------------------------------

let dragging = false;

let lastX = 0;

let lastY = 0;

canvas.addEventListener(

    "mousedown",

    function(event) {{

        dragging = true;

        lastX =
        event.clientX;

        lastY =
        event.clientY;

    }}

);

canvas.addEventListener(

    "mouseup",

    function() {{

        dragging = false;

    }}

);

canvas.addEventListener(

    "mousemove",

    function(event) {{

        if (
            !dragging
        )
        return;

        offsetX +=

        event.clientX
        - lastX;

        offsetY +=

        event.clientY
        - lastY;

        lastX =
        event.clientX;

        lastY =
        event.clientY;

    }}

);

</script>

</body>

</html>
"""

# ---------------------------------------------------------
# STREAMLIT DISPLAY
# ---------------------------------------------------------

st.html(app)
